import fs from "fs";
let f1 = fs.readFileSync("src/components/apb/TeamWorkspaceHeader.tsx", "utf8");
f1 = f1.replace(`import { Round } from "@/lib/firebase/schema";`, `import { Round } from "@/lib/firebase/schema";\nimport { doc, updateDoc } from "firebase/firestore";\nimport { db } from "@/lib/firebase/config";\nimport { useTeamSession } from "@/lib/firebase/teams";`);
f1 = f1.replace(`import { LogOut, WifiOff, Save } from "lucide-react";`, `import { LogOut, WifiOff, Save, LifeBuoy } from "lucide-react";`);
f1 = f1.replace(`export function TeamWorkspaceHeader({\n  teamId,\n  teamDisplayName,\n  teamMembers,\n  round,\n  saveStatus,\n  onLeave,\n}: TeamWorkspaceHeaderProps) {`, `export function TeamWorkspaceHeader({\n  teamId,\n  teamDisplayName,\n  teamMembers,\n  round,\n  saveStatus,\n  onLeave,\n}: TeamWorkspaceHeaderProps) {\n  const { teamData } = useTeamSession();\n  const handleToggleHelp = async () => {\n    try {\n      await updateDoc(doc(db, "teams", teamId), { needsHelp: !(teamData?.needsHelp) });\n    } catch (e) {\n      console.error(e);\n    }\n  };\n`);
const saveStatusIndicator = `{saveStatus === "saving" && (`;
const helpButton = `\n            <button \n              onClick={handleToggleHelp}\n              className={\`flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-mono font-bold transition-all ${teamData?.needsHelp ? "bg-red-500/20 text-red-400 border border-red-500/50 animate-pulse" : "bg-white/5 text-slate-400 border border-white/10 hover:bg-white/10"}\`}\n            >\n              <LifeBuoy className="w-3.5 h-3.5" />\n              <span className="hidden sm:inline">{teamData?.needsHelp ? "HELP REQUESTED" : "REQUEST HELP"}</span>\n            </button>\n`;
f1 = f1.replace(saveStatusIndicator, helpButton + "\\n            " + saveStatusIndicator);
fs.writeFileSync("src/components/apb/TeamWorkspaceHeader.tsx", f1);
let f2 = fs.readFileSync("src/components/apb/ActiveSessionsModal.tsx", "utf8");
f2 = f2.replace(`const displayName = team?.displayName || "";`, `const displayName = team?.displayName || "";\n      const needsHelp = team?.needsHelp;`);
if (!f2.includes("LifeBuoy")) { f2 = f2.replace(`Trash2,`, `Trash2,\n  LifeBuoy,`); }
f2 = f2.replace(`<div className="text-sm font-mono font-bold text-white flex items-center gap-2">\n                        {team?.displayName || teamId}`, `<div className="text-sm font-mono font-bold text-white flex items-center gap-2">\n                        {team?.needsHelp && <LifeBuoy className="w-4 h-4 text-red-500 animate-pulse" title="Needs Help!" />}\n                        {team?.displayName || teamId}`);
fs.writeFileSync("src/components/apb/ActiveSessionsModal.tsx", f2);
let f3 = fs.readFileSync("src/app/organizer/teams/page.tsx", "utf8");
if (!f3.includes("LifeBuoy")) { f3 = f3.replace(`Trash2, Hash, ShieldAlert }`, `Trash2, Hash, ShieldAlert, LifeBuoy }`); }
f3 = f3.replace(`  const handleToggleDisable = async`, `\n  const handleClearHelp = async (teamId: string) => {\n    try {\n      const { doc, updateDoc } = await import("firebase/firestore");\n      const { db } = await import("@/lib/firebase/config");\n      await updateDoc(doc(db, "teams", teamId), { needsHelp: false });\n    } catch (e) {}\n  };\n\n  const handleToggleDisable = async`);
f3 = f3.replace(`<TableCell className="font-mono text-sm text-[var(--color-apb-cyan)] font-bold">\n                        {team.displayName || team.teamId}\n                      </TableCell>`, `<TableCell className="font-mono text-sm text-[var(--color-apb-cyan)] font-bold">\n                        <div className="flex items-center gap-2">\n                          {team.needsHelp && (\n                            <button onClick={() => handleClearHelp(team.teamId)} className="w-5 h-5 rounded bg-red-500/20 flex items-center justify-center border border-red-500/50 animate-pulse hover:bg-red-500/40" title="Clear Help Request">\n                              <LifeBuoy className="w-3.5 h-3.5 text-red-400" />\n                            </button>\n                          )}\n                          {team.displayName || team.teamId}\n                        </div>\n                      </TableCell>`);
fs.writeFileSync("src/app/organizer/teams/page.tsx", f3);
